<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Northeast Ohio Treasure Hunt Demo — Image Manager</title>
<style>
:root{--navy:#0b1f3a;--green:#0f9d67;--line:#dfe7ef;--muted:#677487}*{box-sizing:border-box}body{margin:0;background:#f4f7f8;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#172033}.top{background:linear-gradient(135deg,#0b1f3a,#0f6b4f);color:white;padding:30px 20px}.top>div,.wrap{max-width:1100px;margin:auto}.top h1{margin:8px 0 6px}.top p{margin:0;color:#d8e6eb;line-height:1.55}.wrap{padding:26px 20px 70px}.status{padding:13px 15px;background:#e9f8f0;border:1px solid #a8dfc1;border-radius:12px;margin-bottom:18px;color:#17613f}.notice{padding:13px 15px;background:#fff8dc;border:1px solid #ead48a;border-radius:12px;margin-bottom:22px;color:#674f11}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{background:white;border:1px solid var(--line);border-radius:20px;overflow:hidden;box-shadow:0 10px 28px #0b1f3a0c}.image{aspect-ratio:16/10;background:linear-gradient(145deg,#f8fbfd,#eef5f7);position:relative;display:grid;place-items:center;padding:36px}.image img{width:min(78%,280px);height:auto;max-height:260px;object-fit:contain;display:block;filter:drop-shadow(0 12px 18px #0b1f3a18)}.num{position:absolute;left:12px;top:12px;width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:#0b1f3a;color:white;border:3px solid white;font-size:18px;font-weight:950}.body{padding:20px}.body h2{font-size:23px;margin:4px 0 6px;color:var(--navy)}.type{font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:900;color:var(--green)}.body p{color:var(--muted);line-height:1.5;margin:8px 0 16px}.current{font-size:13px;background:#f6f8fa;border-radius:10px;padding:9px 10px;margin-bottom:12px}.forms{display:grid;gap:10px}.upload{display:grid;grid-template-columns:1fr auto;gap:8px}.upload input[type=file]{width:100%;border:1px solid var(--line);border-radius:10px;padding:9px;background:white}.btn{border:0;border-radius:10px;padding:10px 13px;font-weight:850;cursor:pointer}.primary{background:#0f9d67;color:#fff}.secondary{background:#e9eef3;color:#20344a}.links{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.links a{text-decoration:none;padding:10px 14px;border-radius:10px;background:#0b1f3a;color:white;font-weight:800}@media(max-width:760px){.grid{grid-template-columns:1fr}.upload{grid-template-columns:1fr}}
</style>
</head>
<body>
<header class="top"><div><div style="font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#9ce0bd;font-size:12px">Places Rewards</div><h1>Northeast Ohio Treasure Hunt — Merchant Logo & Card Image Manager</h1><p>Each numbered workflow card has its own independent image slot. The generated default is a clean module badge. Replace it with that participating business's logo or a relevant merchant image without changing the card's copy, function or sequence.</p></div></header>
<main class="wrap">
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="notice"><strong>Recommended image:</strong> merchant logo or clean business-specific graphic, square or near-square, preferably PNG/WebP with a simple background. Do not reuse the same image across unrelated cards. JPG, PNG or WebP up to 5 MB.</div>
<div class="links"><a href="{{ route('demo.northeast-ohio-tom') }}" target="_blank" rel="noopener">Open Tom presentation ↗</a></div>
<div class="grid">
@foreach(($demo['modules'] ?? []) as $module)
@php $num=str_pad($module['sequence'],2,'0',STR_PAD_LEFT);$display=$module['merchant_image'] ?: $module['default_image']; @endphp
<article class="card"><div class="image"><span class="num">{{ $num }}</span><img src="{{ $display }}" alt="{{ $module['title'] }} logo"></div><div class="body"><span class="type">{{ $num }} • {{ $module['label'] }}</span><h2>{{ $module['title'] }}</h2><p>{{ $module['subtitle'] }}</p><div class="current"><strong>Current card visual:</strong> {{ $module['merchant_image'] ? 'Merchant-specific image/logo' : 'Generated module logo badge' }}</div><div class="forms"><form class="upload" method="post" enctype="multipart/form-data" action="{{ route('partner.demo.northeast-ohio-tom.image',['sequence'=>$module['sequence']]) }}">@csrf<input required type="file" name="image" accept="image/jpeg,image/png,image/webp"><button class="btn primary" type="submit">Upload merchant logo/image</button></form>@if($module['merchant_image'])<form method="post" action="{{ route('partner.demo.northeast-ohio-tom.image.reset',['sequence'=>$module['sequence']]) }}">@csrf<button class="btn secondary" type="submit">Restore generated badge</button></form>@endif</div></div></article>
@endforeach
</div></main>
</body></html>