<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ str_pad($module['sequence'],2,'0',STR_PAD_LEFT) }} — {{ $module['title'] }}</title>
<style>
:root{--accent:{{ $module['accent'] ?? '#0f9d67' }};--navy:#0b1f3a;--ink:#172033;--muted:#64748b;--line:#dfe7ef}*{box-sizing:border-box}body{margin:0;background:#f4f8fa;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink)}a{color:inherit}.hero{background:linear-gradient(135deg,#081b32,#0d385b 60%,var(--accent));color:#fff;padding:38px 22px}.wrap{max-width:980px;margin:auto}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;font-weight:900;color:#b9ead2}.hero h1{font-size:clamp(32px,5vw,52px);line-height:1.05;margin:10px 0}.hero p{font-size:19px;line-height:1.55;color:#e5edf4;max-width:830px}.main{padding:28px 22px 70px}.step{display:flex;gap:18px;align-items:center;margin-bottom:22px}.num{width:70px;height:70px;border-radius:18px;background:var(--accent);display:grid;place-items:center;color:#fff;font-weight:950;font-size:28px}.phase{font-size:12px;letter-spacing:.1em;color:var(--accent);font-weight:950}.panel{background:#fff;border:1px solid var(--line);border-radius:20px;padding:24px;margin-bottom:18px;box-shadow:0 12px 28px #102d4410}.panel h2{margin:0 0 10px;color:var(--navy);font-size:24px}.panel p{margin:0;line-height:1.7;color:var(--muted)}.flow{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.flow .box{background:#fff;border:1px solid var(--line);border-radius:16px;padding:18px}.flow strong{display:block;color:var(--accent);font-size:12px;letter-spacing:.07em;text-transform:uppercase;margin-bottom:7px}.example{border-left:5px solid var(--accent);background:#f5faf7;border-radius:12px;padding:18px;font-weight:750;line-height:1.6}.list{display:grid;gap:10px}.item{display:flex;gap:10px;line-height:1.55;font-weight:700}.dot{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:var(--accent);color:#fff;flex:0 0 24px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.btn{text-decoration:none;background:var(--accent);color:#fff;padding:12px 16px;border-radius:11px;font-weight:900}.btn.secondary{background:#e7edf2;color:#18324a}.success{background:#eef9f3;border:1px solid #b7dfca;border-radius:14px;padding:17px;line-height:1.6}.success strong{color:#17613f}.note{font-size:13px;color:#687586;margin-top:12px}@media(max-width:760px){.flow{grid-template-columns:1fr}.step{align-items:flex-start}}
</style>
</head>
<body>
<header class="hero"><div class="wrap"><div class="eyebrow">Places Rewards • Northeast Ohio Treasure Hunt • Module {{ str_pad($module['sequence'],2,'0',STR_PAD_LEFT) }}</div><h1>{{ $module['title'] }}</h1><p>{{ $module['subtitle'] }}</p></div></header>
<main class="main wrap">
<div class="step"><div class="num">{{ str_pad($module['sequence'],2,'0',STR_PAD_LEFT) }}</div><div><div class="phase">WORKFLOW PHASE: {{ $module['workflow_phase'] ?? $module['label'] }}</div><strong>{{ $module['label'] }}</strong></div></div>
<section class="panel"><h2>What this module does</h2><p>{{ $module['description'] }}</p></section>
<section class="flow"><div class="box"><strong>Hunter action</strong>{{ $module['hunter_action'] ?? '' }}</div><div class="box"><strong>Places Rewards action</strong>{{ $module['system_action'] ?? '' }}</div><div class="box"><strong>Merchant value</strong>{{ $module['merchant_value'] ?? '' }}</div></section>
<section class="panel"><h2>Exact demo card content</h2><div class="example">{{ $module['example_content'] ?? '' }}</div><div class="note">This is intentionally different from the other Treasure Hunt modules and demonstrates the specific job of this step.</div></section>
<section class="panel"><h2>What Tom and the participating business should see</h2><div class="list">@foreach(($module['bullets'] ?? []) as $bullet)<div class="item"><span class="dot">✓</span><span>{{ $bullet }}</span></div>@endforeach</div></section>
<section class="success"><strong>Success signal:</strong> {{ $module['success_signal'] ?? '' }}<br><strong>Why it matters:</strong> {{ $module['why_tom'] }}</section>
<div class="actions"><a class="btn secondary" href="{{ route('demo.northeast-ohio-tom') }}#module-{{ str_pad($module['sequence'],2,'0',STR_PAD_LEFT) }}">← Back to workflow</a>@if(!empty($module['live_url']))<a class="btn" href="{{ $module['live_url'] }}" target="_blank" rel="noopener">Open native Places Rewards function ↗</a>@endif @if(!empty($next))<a class="btn" href="{{ route('demo.northeast-ohio-tom.module',['sequence'=>$next['sequence']]) }}">Next Module {{ str_pad($next['sequence'],2,'0',STR_PAD_LEFT) }} →</a>@endif</div>
</main>
</body>
</html>