<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $module['title'] }}</title>
<style>
:root{--navy:#0b1f3a;--green:#0f9d67;--bg:#f5f8fb;--line:#dbe5ee;--muted:#667085;--amber:#b7791f}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:var(--bg);color:#152238}.top{background:linear-gradient(135deg,#071a31,#0e6248);color:#fff;padding:28px 20px}.wrap{max-width:1040px;margin:auto}.crumb{font-size:13px;color:#bfe8d4}.hero{padding:34px 20px 16px}.badge{display:inline-flex;gap:8px;align-items:center}.num{display:grid;place-items:center;width:54px;height:54px;border-radius:50%;background:var(--navy);color:#fff;font-weight:950;font-size:22px}.phase{font-size:12px;letter-spacing:.12em;font-weight:950;color:var(--green)}h1{font-size:40px;line-height:1.06;margin:16px 0 10px}.headline{font-size:21px;font-weight:760;line-height:1.4;color:#334155}.card{margin:22px 20px;background:#fff;border:1px solid var(--line);border-radius:20px;padding:24px;box-shadow:0 12px 30px #0b1f3a0b}.cardcopy{background:#eef8f3;border-left:5px solid var(--green);padding:16px;border-radius:10px;font-weight:850;line-height:1.5}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.box{border:1px solid var(--line);border-radius:14px;padding:17px}.box h3{margin:0 0 8px;font-size:14px;color:var(--green);text-transform:uppercase;letter-spacing:.08em}.box p{margin:0;color:var(--muted);line-height:1.6}.modulelink{margin-top:22px;padding:18px;border:2px solid #bfe3d2;border-radius:14px;background:#f4fbf7}.modulelink h3{margin:0 0 6px;font-size:15px;color:#0b6b48;text-transform:uppercase;letter-spacing:.08em}.modulelink p{margin:0 0 13px;color:#526173;line-height:1.5}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}.btn{display:inline-block;text-decoration:none;border-radius:10px;padding:12px 15px;font-weight:900;background:var(--green);color:#fff}.btn.partner{background:var(--navy)}.btn.alt{background:#e8eef4;color:#17324a}.auth{font-size:11px;font-weight:800;color:var(--amber);margin-left:6px}.nav{display:flex;justify-content:space-between;gap:12px;margin:24px 20px 50px}@media(max-width:720px){.grid{grid-template-columns:1fr}h1{font-size:32px}}
</style></head><body>
<div class="top"><div class="wrap"><div class="crumb"><a href="/demo/treasure-hunt" style="color:inherit">Northeast Ohio Treasure Hunt Demo</a> → {{ $module['label'] }}</div></div></div>
<main class="wrap">
<section class="hero"><div class="badge"><span class="num">{{ str_pad($module['sequence'],2,'0',STR_PAD_LEFT) }}</span><span class="phase">{{ $module['phase'] }}</span></div><h1>{{ $module['title'] }}</h1><div class="headline">{{ $module['headline'] }}</div></section>
<section class="card"><div class="cardcopy">{{ $module['card'] }}</div><p style="line-height:1.7;color:#475569">{{ $module['body'] }}</p>
<div class="grid"><div class="box"><h3>Hunter action</h3><p>{{ $module['customer_action'] }}</p></div><div class="box"><h3>Places Rewards action</h3><p>{{ $module['system_action'] }}</p></div><div class="box"><h3>Why the merchant cares</h3><p>{{ $module['merchant_value'] }}</p></div><div class="box"><h3>What gets measured</h3><p>{{ $module['proof'] }}</p></div></div>
<div class="modulelink">
  <h3>Actual Places Rewards Module</h3>
  @if(!empty($module['actual_note']))<p>{{ $module['actual_note'] }}</p>@else<p>This button opens the real Places Rewards feature/record used by this Treasure Hunt step.</p>@endif
  <div class="actions">
    <a class="btn" href="{{ $module['actual_url'] }}" target="_blank" rel="noopener">{{ $module['actual_label'] }} →</a>@if(!empty($module['actual_auth']))<span class="auth">Partner sign-in required</span>@endif
    @if(!empty($module['secondary_url']))<a class="btn partner" href="{{ $module['secondary_url'] }}" target="_blank" rel="noopener">{{ $module['secondary_label'] }} →</a>@if(!empty($module['secondary_auth']))<span class="auth">Partner/member sign-in may be required</span>@endif@endif
  </div>
</div>
<div class="actions"><a class="btn alt" href="/demo/treasure-hunt">All 12 modules</a></div></section>
<div class="nav"><div>@if($module['prev_url'])<a class="btn alt" href="{{ $module['prev_url'] }}">← Previous module</a>@endif</div><div>@if($module['next_url'])<a class="btn" href="{{ $module['next_url'] }}">Next module →</a>@endif</div></div>
</main></body></html>
